### ISSUE TITLE
EMF (Entity Model Features) Compatibility

### ISSUE THREAD

**Issue by ConnorArc** [ToBinio/real-arrow-tip#4]
is it possible to made compatibility with EMF mod? i try to made this: https://www.planetminecraft.com/texture-pack/vanilla-arrows-plus-2d-model/

but with your arrow tip, but doesnt work :c

**Comment by ToBinio** [comment]
sadly I do not think I can
the problem is i have to change some things about the vanilla arrow rendering to get the tint to show
and EMF just overrides the vanilla renderer.

It might be possible to make a EMF texture pack that is compatible but at least on the Optifine page, I wasn't able to find anything about color tint. so I also don't think this is possible...

sry

**Comment by ConnorArc** [comment]
oh sadly :c so thx anyway
