### ISSUE TITLE
Incompatibility with 1.21.4+

### ISSUE THREAD

**Issue by leeineian** [ToBinio/real-arrow-tip#6]
Take your time.

**Comment by ToBinio** [comment]
just published a [version](https://modrinth.com/mod/real-arrow-tip/version/0.1.1+mc1.21.4) supporting 1.21.4
let me know if you run into any issues!

mojang completely changed how item models work which completely broke the mod so I was procrastinating updating to 1.21.4, which is why there wasn't a 1.21.4
but updating wasn't as bad as I thought!

so, thanks for using my mod!

**Comment by leeineian** [comment]
Ah thank you very much dev 🙇
